server {
    listen 80;
    server_name _;
    etag on;
    ssi on;
    ssi_types text/html;

    root /usr/share/nginx/html;
    index index.html;

    location = /api/playground-access {
      proxy_ssl_server_name on;
      proxy_pass https://nextnative.dev/api/playground-access;
      proxy_set_header Host nextnative.dev;
      proxy_set_header Origin "https://denistarasenko.com";
      proxy_set_header Referer "https://denistarasenko.com/";
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }

    location = /styles.css {
      expires -1;
      add_header Cache-Control "public, no-cache, must-revalidate";
      add_header Surrogate-Control "no-cache";
    }

    # keep static assets cached lightly
    location ~* \.(js|ico)$ {
      expires 7d;
      add_header Cache-Control "public";
    }
  }
